name: "Gereksiz"
highlighter: rouge
permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: '/gereksiz'

# Information for the Atom feed
dmitrydanilich:
   author: "Dmitry Danilich"
   email: "danilichdim@gmail.com"
